### ISSUE TITLE
Can't create Dice object

### ISSUE THREAD

**Issue by noel5550** [noel5550/Project_Blood_Bowl#2]
In Dice.cpp, when trying to compile error message occured:

```
Dice.cpp: In function ‘int main()’:
Dice.cpp:162:28: error: conversion from ‘Dice*’ to non-scalar type ‘Dice’ requested
  Dice dice6 = new Dice(1, 6); //test a faire
                            ^
Dice.cpp:163:27: error: conversion from ‘Dice*’ to non-scalar type ‘Dice’ requested
  Dice dice8 = new Dice(1,8);
                           ^
make: *** [all] Erreur 1
```

Don't know the cause, it happens in main() and concerns the creation of the Dice object. Tried using smart pointers but to no avail. The code is as follows:

``` c++
int main(){
	int test1, test2, test3;
	
	//Dice dice6 = new Dice(1, 6);
	//Dice dice8 = new Dice(1,8);	
	
	Dice dice6 = new Dice(1, 6); //test a faire
	Dice dice8 = new Dice(1,8);
	
	//test1 = dice6->throwDiceDigit();
	//test2 = dice6->throwDiceDigita(dice8);
	
	test1 = dice6.throwDiceDigit();
	test2 = dice6.throwDiceDigita(dice8);
	test3 = dice6.throwDice();
	
	
	std::cout << test1 << std::endl;
	std::cout << test2 << std::endl;
	std::cout << test3 << std::endl;
}

```

Notice the different ways I tried to create Dice. Yes, I included memory.

**Comment by Heartbroken-Git** [comment]
@noel5550 You've broken the commits, apparently commit dfc2b89aa5ca9ccd4ee85d7e334fab25e264d5cb removed everything we did in the last six days. And not only from the repo but from its arborescence too... Did you pull the remote repo before pushing said commit ?

**Comment by noel5550** [comment]
Oh fuck. I knew something went wrong when the terminal froze in the pull request. Fuck me, why can't I reverse this? Ok, making a new branch for myself to prevent future fuck ups.

**Comment by Heartbroken-Git** [comment]
And by the way, your at home git is configured properly apparently... You aren't committing from your GitHub account (but that's just a detail). Did you force the push ? Technically you shouldn't ever need to force a _git push_ command except in really bad scenarios... such as this one xD

As for the test to put back my local repo to the remote I'll do so in a separate branch too, when I have time, to avoid any more disasters.

**Comment by noel5550** [comment]
Nah, I was working at the uni computer. For some reason terminal occasionally freezes up there, so I had to alt ctrl t to open another one to unfreeze Ubuntu. I was too tired to notice I didn't do the pull properly so when I tried to push it gave me a warning, like an idiot I -f it without making 2+2 and why are we speaking English? Mais bon, bref c'etait une connerie entierement de ma part. Il n'y a rien d'entierement perdu? On va faire trois branches, une pour toi, une pour moi, et une autre pour notre sandbox en commun, on laisse master pour des trucs finales.

**Comment by Heartbroken-Git** [comment]
Je sais pas pour l'Anglais, ça paraissait logique comme ton issue était en Anglais xD
Et ouais on va faire les branches pourquoi pas mais faudra probablement faire des PR sur la master chaque semaine si on veut éviter d'avoir une chiée de conflits à régler le dernier jour. Comme on a mon trou chaque lundi on pourra faire ça ensemble ce jour là :smiley:

**Comment by Heartbroken-Git** [comment]
J'ai pas eu le temps de voir pour mon compilateur fou mais pour la construction de Dice essaye ça :

**Comment by noel5550** [comment]
Non c'est bon. J'ai fait des changements de dice dans noel-sandbox. On ne peut que lancer un dé à la fois mais je me suis dit s'il faut lancer plusieurs dés on fera appel à la méthode throwDiceSingle() de Dice plusieurs fois. Au lieu de faire travailler Dice, on fera travailler la classe qui gere les effets comme les classes Wounds, Block, GoForIt, Pass etc qui implementera de l'interface Action. Comme ca on aura un Pattern Strategy de fait.

**Comment by Heartbroken-Git** [comment]
Ok je vois.
D'ailleurs je pense qu'on va pouvoir avoir le pattern State aussi avec les cases du plateau de jeu. Mais là c'est qu'une idée. A voir ce que ça peut donner si j'y réfléchis un peu plus.
Et donc c'est complètement réglé pour Dice ? Tu arrives à le construire et tout ?

**Comment by noel5550** [comment]
Oui, je pensais pattern state pour les cases aussi apres le TD. Et oui, tu peux tester avec un main et ca lance bien un dé et ca donne des résultats aléatoires. Ceci dit, ce n'est pas si simple que de faire 
```c++
rand() % 1 + typeDice_

```
comme je pensais, mais au moins c'est fait et ca marche.
